### PR TITLE
Adds userinfo to value placeholders

### PR DESCRIPTION
**Pull request by solewniczak**
The commit introduces 3 additional placeholders to be used in filters:

- $USER.name$
- $USER.mail$
- $USER.grps$

This may be particularly useful with [structgroup](https://github.com/gkrid/dokuwiki-plugin-structgroup) plugin.

### CODE REVIEW

**Comment by splitbrain** [comment]
Looks useful, but the `applyFilterVars()` method is getting quite large. Could you split it into multiple methods and add some tests?

**Comment by solewniczak** [comment]
Do you think more tests should be provided?

**Comment by solewniczak** [comment]
Do you want to merge this feature into master?

**Comment by solewniczak** [comment]
Do you think this can be merged into master or maybe I should think about some extension mechanism that will make adding additional placeholders to struct possible?

**Pull request merged**
