### PR TITLE
Inline editing

### PR DESCRIPTION
**Pull request by splitbrain**
Implements #58.

Contains parts of #142 (for easier manual testing), should merged after it.

### CODE REVIEW

**Comment by splitbrain** [comment]
@micgro42 please have a look and suggest what should be tested.

**Comment by micgro42** [comment]
Looks good to me.
This is only very optional and only implement it if it's simple to do:

But could do the check of whether opening the popup to the right or the left also for the autocompletion-popup?

**Comment by micgro42** [comment]
Another thing I noticed: If images are used, then only the area of the cell around the image is clickable, i.e. the padding of the `<td>` element. That is ok, but it is possibly not obvious where the image ends and the padding starts. So could we give the images a black border or something similar?

**Comment by micgro42** [comment]
Also I found a bug:
- [ ] The inline-edit for multi-image fields only always uses the first image-input

**Comment by micgro42** [comment]
The issues mentioned above is fixed for cells that originally contain no media. However that bug still persists when the cell already contains one or more images when the page is loaded.
- [ ] multi-image when already at least one image exists uses always the first input

**Comment by splitbrain** [comment]
I just noticed that this bug is present in "normal" edits too: #152

**Comment by micgro42** [comment]
Works for me now :+1:

**Pull request merged**
