### PR TITLE
Fixed issue #437, filtering DateTime

### PR DESCRIPTION
**Pull request by cmacmackin**
Applying a filter on a DateTime column in an aggregation was causing an uncaught error to occur and prevent the page being rendered at all (see #437). Fortunately, this turned out to be a very simple issue to resolve; it was just an issue with a variable not being declared in the right place.

### CODE REVIEW

**Comment by cmacmackin** [comment]
**Bump**

Could this code be checked and merged? It's a very minor change but fixes a bad error. I'm currently using this patched version of `struct` on my wiki without problems, but it would be nice to have it merged so I don't need to reapply it whenever I upgrade the plugin.

**Comment by splitbrain** [comment]
Any chance you could add a unit test for this?

**Comment by cmacmackin** [comment]
Sure, I'll try to get to that later today.

**Comment by cmacmackin** [comment]
OK, added a simple unit test. Confirmed that it failed without my change to the DateTime class and passes now.

**Comment by splitbrain** [comment]
awesome! thank you!

**Comment by splitbrain** [comment]
I just noticed: you forgot to check in the datetime schema json. Can you add it to your branch please?

**Comment by cmacmackin** [comment]
Oh sorry about that. I thought it was a pre-existing file. Can't even remember when I would have generated that! I'm at work away from my personal computer at the moment but will do it this evening.

**Pull request merged**
