### PR TITLE
Prefix Summary type with "Abstract" to hide it in Schema Editor.

### LINKED ISSUE #451: Type "Summary" should not be available in schema editor

### PR DESCRIPTION
**Pull request by solewniczak**
Fixes #451

### CODE REVIEW

**Comment by splitbrain** [comment]
Hmm, I don't like to prefix a class name with `Abstract` when it's not an abstract class.

**Comment by solewniczak** [comment]
Alternatively we can add an exception in meta/Column.php. Do you think this will be better solution?

**Comment by splitbrain** [comment]
I was thinking of a `isHidden()` method, but that means to instantiate the class before throwing it away again. Maybe using a different prefix than Abstract would be the easiest and still somewhat clean solution?

**Comment by solewniczak** [comment]
Maybe just "Hidden" as a prefix or make isHidden method static.

**Comment by splitbrain** [comment]
Maybe `Auto`, so this becomes `AutoSummary` - it indicates that this is a field that is `auto`matically calculated/filled and can not be used as schema field.

**Comment by splitbrain** [comment]
Looks like some of the tests need adjustments. @solewniczak can you have a look?

**Pull request merged**
