### PR TITLE
Add an event for custom schema data rendering

### PR DESCRIPTION
**Pull request by fschrempf**
In order to hook in a custom renderer for the schema data on the
page we add a new event PLUGIN_STRUCT_RENDER_SCHEMA_DATA and use
the current table representation as default implementation.

### CODE REVIEW

**Comment by fschrempf** [comment]
See here for a use-case description: https://github.com/cosmocode/dokuwiki-plugin-struct/pull/547#issuecomment-770446257

**Comment by fschrempf** [comment]
And here is the first version of a plugin to make use of this: https://github.com/fschrempf/dokuwiki-plugin-structtemplating

**Comment by fschrempf** [comment]
I rebased this to account for the PHP 8 changes in master and fixed one small issue.

@splitbrain @annda As this is a follow-up of #547, would you mind taking a look at this? Thanks!

**Comment by annda** [comment]
Thanks for the contribution.

**Pull request merged**
