### PR TITLE
IN operator in struct filter

### PR DESCRIPTION
**Pull request by solewniczak**
This commit introduces additional comparator: "IN" into struct filter. The syntax is:
`structfield IN ("a", "b", "c")`
This is simply translated into:
`structfield = "a" OR structfield = "b" OR structfield = "c"`
I've found the IN syntax more readeable in some situations.

### CODE REVIEW

**Comment by splitbrain** [comment]
Hmm, you're using the Doku Lexer to parse the filter string into an array, right? That's interesting and quite clever.

I'm not sure about the term `RowValue` - it took me a while to understand what that value is. Would `FilterValueList` make more sense?

**Comment by solewniczak** [comment]
Do you think more tests should be provided?

**Comment by splitbrain** [comment]
Sorry for taking so long. Can you update the documentation?

**Comment by solewniczak** [comment]
Documentation updated. Thank you for merge.

**Pull request merged**
