### PR TITLE
Enable using page struct data in dw2pdf templates

### PR DESCRIPTION
**Pull request by annda**
This PR makes use of https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/pull/387
It adds the struct data of the page being exported to dw2pdf's replacement array. That way we can use struct placeholders in pdf templates, like `@PLUGIN_STRUCT_schema_fieldname@`

### CODE REVIEW

**Comment by splitbrain** [comment]
Could we have a unit test for this?

**Comment by splitbrain** [comment]
Can you add docs to https://www.dokuwiki.org/plugin:struct:integrations please?

**Comment by Juergen-aus-Koeln** [comment]
What is to do if the definition of a schema or a fieldname contains underscore?

**Comment by annda** [comment]
@Juergen-aus-Koeln Good point, I have to fix this.

**Pull request merged**
